spring.datasource.url=jdbc:mysql://localhost:3306/snsdatas
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234

kakao.client-id=t
kakao.client-secret=t

naver.client-id=t
naver.client-secret=t

google.client-id=t
google.client-secret=t